version: '3'
services:
    #사용 데이터베이스
    mysql:
        image: mysql
        restart: always
        container_name: mysqltest
        ports:
          - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE : redmine
            TZ: Asia/Seoul
    
    redmine:
        image: redmine
        restart : always
        container_name : redminetest
        ports:
          - "3000:3000"
        link:
          mysql:mysql
