version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: redmine
    ports:
      - "3308:3306"

  redmine:
    image: redmine
    ports:
      - "3000:3000"
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_PORT: 3306
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: root
      REDMINE_DB_PASSWORD: secret
    depends_on:
      - mysql

  server:
    image: server
    container_name: server
    networks:
      - opensw-network
    -ports:
      - "8082:8082"